// @generated by protoc-gen-connect-web v0.3.1 with parameter "target=ts"
// @generated from file debug/service.proto (package spotsie.debug.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {GetTicksRequest, GetTicksResponse, TickStreamRequest, TickStreamResponse} from "./service_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service spotsie.debug.v1.DebugService
 */
export const DebugService = {
  typeName: "spotsie.debug.v1.DebugService",
  methods: {
    /**
     * @generated from rpc spotsie.debug.v1.DebugService.GetTicks
     */
    getTicks: {
      name: "GetTicks",
      I: GetTicksRequest,
      O: GetTicksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.debug.v1.DebugService.TickStream
     */
    tickStream: {
      name: "TickStream",
      I: TickStreamRequest,
      O: TickStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

