// @generated by protoc-gen-es v0.2.1 with parameter "target=js+dts"
// @generated from file debug/service.proto (package spotsie.debug.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3, Timestamp} from "@bufbuild/protobuf";
import {Tick} from "./debug_pb.js";

/**
 * Get ticks in specified time range
 *
 * @generated from message spotsie.debug.v1.GetTicksRequest
 */
export const GetTicksRequest = proto3.makeMessageType(
  "spotsie.debug.v1.GetTicksRequest",
  () => [
    { no: 1, name: "from_time", kind: "message", T: Timestamp },
    { no: 2, name: "to_time", kind: "message", T: Timestamp },
  ],
);

/**
 * @generated from message spotsie.debug.v1.GetTicksResponse
 */
export const GetTicksResponse = proto3.makeMessageType(
  "spotsie.debug.v1.GetTicksResponse",
  () => [
    { no: 1, name: "ticks", kind: "message", T: Tick, repeated: true },
  ],
);

/**
 * @generated from message spotsie.debug.v1.TickStreamRequest
 */
export const TickStreamRequest = proto3.makeMessageType(
  "spotsie.debug.v1.TickStreamRequest",
  [],
);

/**
 * @generated from message spotsie.debug.v1.TickStreamResponse
 */
export const TickStreamResponse = proto3.makeMessageType(
  "spotsie.debug.v1.TickStreamResponse",
  () => [
    { no: 1, name: "tick", kind: "message", T: Tick },
  ],
);

