// @generated by protoc-gen-connect-web v0.9.1
// @generated from file subject/v1/service.proto (package subject.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAllSubjectsRequest, GetSubjectsTelemetryRequest, GetSubjectsTelemetryResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service subject.v1.SubjectService
 */
export declare const SubjectService: {
  readonly typeName: "subject.v1.SubjectService",
  readonly methods: {
    /**
     * @generated from rpc subject.v1.SubjectService.GetAllSubjects
     */
    readonly getAllSubjects: {
      readonly name: "GetAllSubjects",
      readonly I: typeof GetAllSubjectsRequest,
      readonly O: typeof GetAllSubjectsRequest,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc subject.v1.SubjectService.GetSubjectsTelemetry
     */
    readonly getSubjectsTelemetry: {
      readonly name: "GetSubjectsTelemetry",
      readonly I: typeof GetSubjectsTelemetryRequest,
      readonly O: typeof GetSubjectsTelemetryResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

