// @generated by protoc-gen-connect-web v0.11.0
// @generated from file subject/v1/service.proto (package subject.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAllSubjectsRequest, GetAllSubjectsResponse, GetLatestSubjectsTelemetryRequest, GetLatestSubjectsTelemetryResponse, GetSubjectsTelemetryRequest, GetSubjectsTelemetryResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service subject.v1.SubjectService
 */
export const SubjectService = {
  typeName: "subject.v1.SubjectService",
  methods: {
    /**
     * @generated from rpc subject.v1.SubjectService.GetAllSubjects
     */
    getAllSubjects: {
      name: "GetAllSubjects",
      I: GetAllSubjectsRequest,
      O: GetAllSubjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves all telemetry data for specified subjects in selected time period
     *
     * @generated from rpc subject.v1.SubjectService.GetSubjectsTelemetry
     */
    getSubjectsTelemetry: {
      name: "GetSubjectsTelemetry",
      I: GetSubjectsTelemetryRequest,
      O: GetSubjectsTelemetryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves only the most recent sample of telemetry data for specified subjects
     *
     * @generated from rpc subject.v1.SubjectService.GetLatestSubjectsTelemetry
     */
    getLatestSubjectsTelemetry: {
      name: "GetLatestSubjectsTelemetry",
      I: GetLatestSubjectsTelemetryRequest,
      O: GetLatestSubjectsTelemetryResponse,
      kind: MethodKind.Unary,
    },
  }
};

