// @generated by protoc-gen-connect-query v0.2.3
// @generated from file subject/v1/service.proto (package subject.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { UnaryHooks } from "@bufbuild/connect-query";
import { GetAllSubjectsRequest, GetSubjectsTelemetryRequest, GetSubjectsTelemetryResponse } from "./service_pb.js";

export const getAllSubjects: UnaryHooks<GetAllSubjectsRequest, GetAllSubjectsRequest>;
export const getSubjectsTelemetry: UnaryHooks<GetSubjectsTelemetryRequest, GetSubjectsTelemetryResponse>;
