// @generated by protoc-gen-connect-web v0.9.1
// @generated from file subject/v1/service.proto (package subject.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAllSubjectsRequest, GetSubjectsTelemetryRequest, GetSubjectsTelemetryResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service subject.v1.SubjectService
 */
export const SubjectService = {
  typeName: "subject.v1.SubjectService",
  methods: {
    /**
     * @generated from rpc subject.v1.SubjectService.GetAllSubjects
     */
    getAllSubjects: {
      name: "GetAllSubjects",
      I: GetAllSubjectsRequest,
      O: GetAllSubjectsRequest,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc subject.v1.SubjectService.GetSubjectsTelemetry
     */
    getSubjectsTelemetry: {
      name: "GetSubjectsTelemetry",
      I: GetSubjectsTelemetryRequest,
      O: GetSubjectsTelemetryResponse,
      kind: MethodKind.Unary,
    },
  }
};

