// @generated by protoc-gen-connect-web v0.11.0
// @generated from file subject/v1/service.proto (package subject.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAllSubjectsRequest, GetAllSubjectsResponse, GetLatestSubjectsTelemetryRequest, GetLatestSubjectsTelemetryResponse, GetSubjectsTelemetryRequest, GetSubjectsTelemetryResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service subject.v1.SubjectService
 */
export declare const SubjectService: {
  readonly typeName: "subject.v1.SubjectService",
  readonly methods: {
    /**
     * @generated from rpc subject.v1.SubjectService.GetAllSubjects
     */
    readonly getAllSubjects: {
      readonly name: "GetAllSubjects",
      readonly I: typeof GetAllSubjectsRequest,
      readonly O: typeof GetAllSubjectsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Retrieves all telemetry data for specified subjects in selected time period
     *
     * @generated from rpc subject.v1.SubjectService.GetSubjectsTelemetry
     */
    readonly getSubjectsTelemetry: {
      readonly name: "GetSubjectsTelemetry",
      readonly I: typeof GetSubjectsTelemetryRequest,
      readonly O: typeof GetSubjectsTelemetryResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Retrieves only the most recent sample of telemetry data for specified subjects
     *
     * @generated from rpc subject.v1.SubjectService.GetLatestSubjectsTelemetry
     */
    readonly getLatestSubjectsTelemetry: {
      readonly name: "GetLatestSubjectsTelemetry",
      readonly I: typeof GetLatestSubjectsTelemetryRequest,
      readonly O: typeof GetLatestSubjectsTelemetryResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

