// @generated by protoc-gen-connect-web v0.9.1
// @generated from file deployment/v1/service.proto (package deployment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddPositioningReferentRequest, AddPositioningReferentResponse, CreateDeploymentRequest, CreateDeploymentResponse, CreateOrganizationRequest, CreateOrganizationResponse, CreateZoneRequest, CreateZoneResponse, DeleteZoneRequest, DeleteZoneResponse, GetDeploymentRequest, GetDeploymentResponse, GetDeploymentsRequest, GetDeploymentsResponse, GetDeploymentStateRequest, GetDeploymentStateResponse, GetOrganizationRequest, GetOrganizationResponse, GetOrganizationsRequest, GetOrganizationsResponse, GetPositioningReferentRequest, GetPositioningReferentResponse, GetPositioningReferentsRequest, GetPositioningReferentsResponse, GetZoneRequest, GetZoneResponse, GetZonesRequest, GetZonesResponse, SetDeploymentStateRequest, SetDeploymentStateResponse, UpdateDeploymentRequest, UpdateDeploymentResponse, UpdatePositioningReferentRequest, UpdatePositioningReferentResponse, UpdateZoneRequest, UpdateZoneResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service deployment.v1.DeploymentService
 */
export const DeploymentService = {
  typeName: "deployment.v1.DeploymentService",
  methods: {
    /**
     * Deployment ops
     *
     * @generated from rpc deployment.v1.DeploymentService.GetDeployments
     */
    getDeployments: {
      name: "GetDeployments",
      I: GetDeploymentsRequest,
      O: GetDeploymentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.CreateDeployment
     */
    createDeployment: {
      name: "CreateDeployment",
      I: CreateDeploymentRequest,
      O: CreateDeploymentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.UpdateDeployment
     */
    updateDeployment: {
      name: "UpdateDeployment",
      I: UpdateDeploymentRequest,
      O: UpdateDeploymentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.GetDeployment
     */
    getDeployment: {
      name: "GetDeployment",
      I: GetDeploymentRequest,
      O: GetDeploymentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.GetDeploymentState
     */
    getDeploymentState: {
      name: "GetDeploymentState",
      I: GetDeploymentStateRequest,
      O: GetDeploymentStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.SetDeploymentState
     */
    setDeploymentState: {
      name: "SetDeploymentState",
      I: SetDeploymentStateRequest,
      O: SetDeploymentStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Zone ops
     *
     * @generated from rpc deployment.v1.DeploymentService.CreateZone
     */
    createZone: {
      name: "CreateZone",
      I: CreateZoneRequest,
      O: CreateZoneResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.DeleteZone
     */
    deleteZone: {
      name: "DeleteZone",
      I: DeleteZoneRequest,
      O: DeleteZoneResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.UpdateZone
     */
    updateZone: {
      name: "UpdateZone",
      I: UpdateZoneRequest,
      O: UpdateZoneResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.GetZones
     */
    getZones: {
      name: "GetZones",
      I: GetZonesRequest,
      O: GetZonesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.GetZone
     */
    getZone: {
      name: "GetZone",
      I: GetZoneRequest,
      O: GetZoneResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Positioning Referent ops 
     *
     * @generated from rpc deployment.v1.DeploymentService.AddPositioningReferent
     */
    addPositioningReferent: {
      name: "AddPositioningReferent",
      I: AddPositioningReferentRequest,
      O: AddPositioningReferentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.UpdatePositioningReferent
     */
    updatePositioningReferent: {
      name: "UpdatePositioningReferent",
      I: UpdatePositioningReferentRequest,
      O: UpdatePositioningReferentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.GetPositioningReferents
     */
    getPositioningReferents: {
      name: "GetPositioningReferents",
      I: GetPositioningReferentsRequest,
      O: GetPositioningReferentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.GetPositioningReferent
     */
    getPositioningReferent: {
      name: "GetPositioningReferent",
      I: GetPositioningReferentRequest,
      O: GetPositioningReferentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * * Organization ops* //
     *
     * @generated from rpc deployment.v1.DeploymentService.CreateOrganization
     */
    createOrganization: {
      name: "CreateOrganization",
      I: CreateOrganizationRequest,
      O: CreateOrganizationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.GetOrganization
     */
    getOrganization: {
      name: "GetOrganization",
      I: GetOrganizationRequest,
      O: GetOrganizationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc deployment.v1.DeploymentService.GetOrganizations
     */
    getOrganizations: {
      name: "GetOrganizations",
      I: GetOrganizationsRequest,
      O: GetOrganizationsResponse,
      kind: MethodKind.Unary,
    },
  }
};

