// @generated by protoc-gen-connect-web v0.11.0
// @generated from file watchdog/v1/service.proto (package watchdog.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateJobRequest, CreateJobResponse, CreateSubjectGroupRequest, CreateSubjectGroupResponse, DeleteJobRequest, DeleteJobResponse, GetEventsRequest, GetEventsResponse, GetJobsRequest, GetJobsResponse, GetSubjectGroupsRequest, GetSubjectGroupsResponse, UpdateSubjectGroupRequest, UpdateSubjectGroupResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service watchdog.v1.WatchdogService
 */
export declare const WatchdogService: {
  readonly typeName: "watchdog.v1.WatchdogService",
  readonly methods: {
    /**
     * @generated from rpc watchdog.v1.WatchdogService.GetJobs
     */
    readonly getJobs: {
      readonly name: "GetJobs",
      readonly I: typeof GetJobsRequest,
      readonly O: typeof GetJobsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc watchdog.v1.WatchdogService.CreateJob
     */
    readonly createJob: {
      readonly name: "CreateJob",
      readonly I: typeof CreateJobRequest,
      readonly O: typeof CreateJobResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * rpc UpdateJob(UpdateJobRequest) returns (UpdateJobResponse);
     *
     * @generated from rpc watchdog.v1.WatchdogService.DeleteJob
     */
    readonly deleteJob: {
      readonly name: "DeleteJob",
      readonly I: typeof DeleteJobRequest,
      readonly O: typeof DeleteJobResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc watchdog.v1.WatchdogService.GetSubjectGroups
     */
    readonly getSubjectGroups: {
      readonly name: "GetSubjectGroups",
      readonly I: typeof GetSubjectGroupsRequest,
      readonly O: typeof GetSubjectGroupsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc watchdog.v1.WatchdogService.CreateSubjectGroup
     */
    readonly createSubjectGroup: {
      readonly name: "CreateSubjectGroup",
      readonly I: typeof CreateSubjectGroupRequest,
      readonly O: typeof CreateSubjectGroupResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * rpc DeleteSubjectGroup(DeleteJobRequest) returns (DeleteJobResponse);
     *
     * @generated from rpc watchdog.v1.WatchdogService.UpdateSubjectGroup
     */
    readonly updateSubjectGroup: {
      readonly name: "UpdateSubjectGroup",
      readonly I: typeof UpdateSubjectGroupRequest,
      readonly O: typeof UpdateSubjectGroupResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc watchdog.v1.WatchdogService.GetEvents
     */
    readonly getEvents: {
      readonly name: "GetEvents",
      readonly I: typeof GetEventsRequest,
      readonly O: typeof GetEventsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

