// @generated by protoc-gen-es v1.1.1
// @generated from file watchdog/v1/subject_group.proto (package watchdog.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Audit } from "../../domain/v1/domain_pb.js";

/**
 * @generated from message watchdog.v1.SubjectGroup
 */
export const SubjectGroup = proto3.makeMessageType(
  "watchdog.v1.SubjectGroup",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "namespace_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "subject_ids", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
    { no: 6, name: "audit", kind: "message", T: Audit },
  ],
);

