// @generated by protoc-gen-es v1.0.0 with parameter "target=js+dts"
// @generated from file watchdog/v1/subject_group.proto (package watchdog.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message watchdog.v1.Audit
 */
export const Audit = proto3.makeMessageType(
  "watchdog.v1.Audit",
  () => [
    { no: 1, name: "created_at", kind: "message", T: Timestamp, opt: true },
    { no: 2, name: "updated_at", kind: "message", T: Timestamp, opt: true },
    { no: 3, name: "deleted_at", kind: "message", T: Timestamp, opt: true },
  ],
);

/**
 * @generated from message watchdog.v1.SubjectGroup
 */
export const SubjectGroup = proto3.makeMessageType(
  "watchdog.v1.SubjectGroup",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "namespace_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "subject_ids", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
    { no: 6, name: "audit", kind: "message", T: Audit },
  ],
);

