// @generated by protoc-gen-es v1.3.1
// @generated from file watchdog/v1/watchdog.proto (package watchdog.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Duration, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message watchdog.v1.Job
 */
export const Job = proto3.makeMessageType(
  "watchdog.v1.Job",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "namespace_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "subject_group_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "config", kind: "message", T: Job_Config },
  ],
);

/**
 * @generated from message watchdog.v1.Job.Config
 */
export const Job_Config = proto3.makeMessageType(
  "watchdog.v1.Job.Config",
  () => [
    { no: 10, name: "no_activity", kind: "message", T: Job_Config_NoActivity, oneof: "kind" },
    { no: 11, name: "activity", kind: "message", T: Job_Config_Activity, oneof: "kind" },
    { no: 12, name: "similar_movement", kind: "message", T: Job_Config_SimilarMovement, oneof: "kind" },
    { no: 13, name: "zone_overstay", kind: "message", T: Job_Config_ZoneOverstay, oneof: "kind" },
    { no: 14, name: "no_movement", kind: "message", T: Job_Config_NoMovement, oneof: "kind" },
    { no: 15, name: "temperature_limit", kind: "message", T: Job_Config_TemperatureLimit, oneof: "kind" },
    { no: 16, name: "low_battery", kind: "message", T: Job_Config_LowBattery, oneof: "kind" },
    { no: 17, name: "button_press", kind: "message", T: Job_Config_ButtonPress, oneof: "kind" },
  ],
  {localName: "Job_Config"},
);

/**
 * @generated from message watchdog.v1.Job.Config.NoActivity
 */
export const Job_Config_NoActivity = proto3.makeMessageType(
  "watchdog.v1.Job.Config.NoActivity",
  () => [
    { no: 1, name: "duration_threshold", kind: "message", T: Duration },
  ],
  {localName: "Job_Config_NoActivity"},
);

/**
 * @generated from message watchdog.v1.Job.Config.Activity
 */
export const Job_Config_Activity = proto3.makeMessageType(
  "watchdog.v1.Job.Config.Activity",
  [],
  {localName: "Job_Config_Activity"},
);

/**
 * @generated from message watchdog.v1.Job.Config.SimilarMovement
 */
export const Job_Config_SimilarMovement = proto3.makeMessageType(
  "watchdog.v1.Job.Config.SimilarMovement",
  [],
  {localName: "Job_Config_SimilarMovement"},
);

/**
 * @generated from message watchdog.v1.Job.Config.ZoneOverstay
 */
export const Job_Config_ZoneOverstay = proto3.makeMessageType(
  "watchdog.v1.Job.Config.ZoneOverstay",
  () => [
    { no: 1, name: "duration_threshold", kind: "message", T: Duration },
  ],
  {localName: "Job_Config_ZoneOverstay"},
);

/**
 * @generated from message watchdog.v1.Job.Config.NoMovement
 */
export const Job_Config_NoMovement = proto3.makeMessageType(
  "watchdog.v1.Job.Config.NoMovement",
  () => [
    { no: 1, name: "duration_threshold", kind: "message", T: Duration },
  ],
  {localName: "Job_Config_NoMovement"},
);

/**
 * @generated from message watchdog.v1.Job.Config.TemperatureLimit
 */
export const Job_Config_TemperatureLimit = proto3.makeMessageType(
  "watchdog.v1.Job.Config.TemperatureLimit",
  () => [
    { no: 1, name: "max_temperature", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "min_temperature", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
  {localName: "Job_Config_TemperatureLimit"},
);

/**
 * @generated from message watchdog.v1.Job.Config.LowBattery
 */
export const Job_Config_LowBattery = proto3.makeMessageType(
  "watchdog.v1.Job.Config.LowBattery",
  () => [
    { no: 1, name: "min_allowed_battery_level", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ],
  {localName: "Job_Config_LowBattery"},
);

/**
 * @generated from message watchdog.v1.Job.Config.ButtonPress
 */
export const Job_Config_ButtonPress = proto3.makeMessageType(
  "watchdog.v1.Job.Config.ButtonPress",
  [],
  {localName: "Job_Config_ButtonPress"},
);

