// @generated by protoc-gen-connect-web v0.8.3
// @generated from file location/v1/service.proto (package location.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetLatestSubjectLocationRequest, GetLatestSubjectLocationResponse, GetLatestSubjectPositionRequest, GetLatestSubjectPositionResponse, GetLocationHistoryRequest, GetLocationHistoryResponse, GetLocationRecordsRequest, GetLocationRecordsResponse, GetRealtimeLocationRequest, GetRealtimeLocationResponse, GetSubjectLocationsAtRequest, GetSubjectLocationsAtResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service location.v1.LocationService
 */
export const LocationService = {
  typeName: "location.v1.LocationService",
  methods: {
    /**
     * Compressed location history based on zones
     *
     * @generated from rpc location.v1.LocationService.GetLocationHistory
     */
    getLocationHistory: {
      name: "GetLocationHistory",
      I: GetLocationHistoryRequest,
      O: GetLocationHistoryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Point in time location records based on zone and/or coordinates
     *
     * @generated from rpc location.v1.LocationService.GetLocationRecords
     */
    getLocationRecords: {
      name: "GetLocationRecords",
      I: GetLocationRecordsRequest,
      O: GetLocationRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc location.v1.LocationService.GetRealtimeLocation
     */
    getRealtimeLocation: {
      name: "GetRealtimeLocation",
      I: GetRealtimeLocationRequest,
      O: GetRealtimeLocationResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc location.v1.LocationService.GetSubjectLocationsAt
     */
    getSubjectLocationsAt: {
      name: "GetSubjectLocationsAt",
      I: GetSubjectLocationsAtRequest,
      O: GetSubjectLocationsAtResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deprecated: GetLatestSubjectPosition is deprecated, use GetLatestSubjectLocation instead
     *
     * @generated from rpc location.v1.LocationService.GetLatestSubjectPosition
     */
    getLatestSubjectPosition: {
      name: "GetLatestSubjectPosition",
      I: GetLatestSubjectPositionRequest,
      O: GetLatestSubjectPositionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc location.v1.LocationService.GetLatestSubjectLocation
     */
    getLatestSubjectLocation: {
      name: "GetLatestSubjectLocation",
      I: GetLatestSubjectLocationRequest,
      O: GetLatestSubjectLocationResponse,
      kind: MethodKind.Unary,
    },
  }
};

