// @generated by protoc-gen-connect-query v0.4.0
// @generated from file location/v1/service.proto (package location.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { UnaryHooks } from "@bufbuild/connect-query";
import { GetLatestSubjectLocationRequest, GetLatestSubjectLocationResponse, GetLatestSubjectPositionRequest, GetLatestSubjectPositionResponse, GetLocationHistoryRequest, GetLocationHistoryResponse, GetLocationRecordsRequest, GetLocationRecordsResponse, GetSubjectLocationsAtRequest, GetSubjectLocationsAtResponse } from "./service_pb.js";

export const getLocationHistory: UnaryHooks<GetLocationHistoryRequest, GetLocationHistoryResponse>;
export const getLocationRecords: UnaryHooks<GetLocationRecordsRequest, GetLocationRecordsResponse>;
export const getSubjectLocationsAt: UnaryHooks<GetSubjectLocationsAtRequest, GetSubjectLocationsAtResponse>;
export const getLatestSubjectPosition: UnaryHooks<GetLatestSubjectPositionRequest, GetLatestSubjectPositionResponse>;
export const getLatestSubjectLocation: UnaryHooks<GetLatestSubjectLocationRequest, GetLatestSubjectLocationResponse>;
