// @generated by protoc-gen-connect-web v0.3.1 with parameter "target=ts"
// @generated from file deployment/service.proto (package spotsie.deployment.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {AddPositioningReferentRequest, AddPositioningReferentResponse, CreateDeploymentRequest, CreateDeploymentResponse, CreateMemberInviteRequest, CreateMemberInviteResponse, CreateOrganizationRequest, CreateOrganizationResponse, CreateZoneRequest, CreateZoneResponse, DeleteZoneRequest, DeleteZoneResponse, GetDeploymentsRequest, GetDeploymentsResponse, GetMembersRequest, GetMembersResponse, GetOrganizationRequest, GetOrganizationResponse, GetOrganizationsRequest, GetOrganizationsResponse, GetPositioningReferentRequest, GetPositioningReferentResponse, GetPositioningReferentsRequest, GetPositioningReferentsResponse, GetSignUpInviteRequest, GetSignupInviteResponse, GetZoneRequest, GetZoneResponse, GetZonesRequest, GetZonesResponse, PasswordRecoveryRequest, PasswordRecoveryResponse, SignInRequest, SignInResponse, SignUpRequest, SignUpResponse, UpdateDeploymentRequest, UpdateDeploymentResponse, UpdatePositioningReferentRequest, UpdatePositioningReferentResponse, UpdateZoneRequest, UpdateZoneResponse} from "./service_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service spotsie.deployment.v1.DeploymentApi
 */
export const DeploymentApi = {
  typeName: "spotsie.deployment.v1.DeploymentApi",
  methods: {
    /**
     * Deployment ops
     *
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.GetDeployments
     */
    getDeployments: {
      name: "GetDeployments",
      I: GetDeploymentsRequest,
      O: GetDeploymentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.CreateDeployment
     */
    createDeployment: {
      name: "CreateDeployment",
      I: CreateDeploymentRequest,
      O: CreateDeploymentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.UpdateDeployment
     */
    updateDeployment: {
      name: "UpdateDeployment",
      I: UpdateDeploymentRequest,
      O: UpdateDeploymentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Zone ops
     *
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.CreateZone
     */
    createZone: {
      name: "CreateZone",
      I: CreateZoneRequest,
      O: CreateZoneResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.DeleteZone
     */
    deleteZone: {
      name: "DeleteZone",
      I: DeleteZoneRequest,
      O: DeleteZoneResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.UpdateZone
     */
    updateZone: {
      name: "UpdateZone",
      I: UpdateZoneRequest,
      O: UpdateZoneResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.GetZones
     */
    getZones: {
      name: "GetZones",
      I: GetZonesRequest,
      O: GetZonesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.GetZone
     */
    getZone: {
      name: "GetZone",
      I: GetZoneRequest,
      O: GetZoneResponse,
      kind: MethodKind.Unary,
    },
    /**
     * * Organization ops* //
     *
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.AddPositioningReferent
     */
    addPositioningReferent: {
      name: "AddPositioningReferent",
      I: AddPositioningReferentRequest,
      O: AddPositioningReferentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.UpdatePositioningReferent
     */
    updatePositioningReferent: {
      name: "UpdatePositioningReferent",
      I: UpdatePositioningReferentRequest,
      O: UpdatePositioningReferentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.GetPositioningReferents
     */
    getPositioningReferents: {
      name: "GetPositioningReferents",
      I: GetPositioningReferentsRequest,
      O: GetPositioningReferentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.GetPositioningReferent
     */
    getPositioningReferent: {
      name: "GetPositioningReferent",
      I: GetPositioningReferentRequest,
      O: GetPositioningReferentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.CreateOrganization
     */
    createOrganization: {
      name: "CreateOrganization",
      I: CreateOrganizationRequest,
      O: CreateOrganizationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.GetOrganization
     */
    getOrganization: {
      name: "GetOrganization",
      I: GetOrganizationRequest,
      O: GetOrganizationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.GetOrganizations
     */
    getOrganizations: {
      name: "GetOrganizations",
      I: GetOrganizationsRequest,
      O: GetOrganizationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.GetMembers
     */
    getMembers: {
      name: "GetMembers",
      I: GetMembersRequest,
      O: GetMembersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.CreateMemberInvite
     */
    createMemberInvite: {
      name: "CreateMemberInvite",
      I: CreateMemberInviteRequest,
      O: CreateMemberInviteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * *Auth* //
     *
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.SignIn
     */
    signIn: {
      name: "SignIn",
      I: SignInRequest,
      O: SignInResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.SignUp
     */
    signUp: {
      name: "SignUp",
      I: SignUpRequest,
      O: SignUpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.GetSignUpInvite
     */
    getSignUpInvite: {
      name: "GetSignUpInvite",
      I: GetSignUpInviteRequest,
      O: GetSignupInviteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.deployment.v1.DeploymentApi.PasswordRecovery
     */
    passwordRecovery: {
      name: "PasswordRecovery",
      I: PasswordRecoveryRequest,
      O: PasswordRecoveryResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

