// @generated by protoc-gen-es v1.3.1
// @generated from file notification/v1/notification.proto (package notification.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message notification.v1.MailAlert
 */
export const MailAlert = proto3.makeMessageType(
  "notification.v1.MailAlert",
  () => [
    { no: 1, name: "max_send", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "to", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "cc", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "bcc", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message notification.v1.GithubAlert
 */
export const GithubAlert = proto3.makeMessageType(
  "notification.v1.GithubAlert",
  () => [
    { no: 1, name: "max_send", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "assignees", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "labels", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message notification.v1.Notification
 */
export const Notification = proto3.makeMessageType(
  "notification.v1.Notification",
  () => [
    { no: 1, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "event_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "mail_alert", kind: "message", T: MailAlert, repeated: true },
    { no: 7, name: "github_alert", kind: "message", T: GithubAlert, repeated: true },
  ],
);

