// @generated by protoc-gen-connect-web v0.9.1
// @generated from file notification/v1/service.proto (package notification.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateNotificationRequest, CreateNotificationResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service notification.v1.NotificationService
 */
export const NotificationService = {
  typeName: "notification.v1.NotificationService",
  methods: {
    /**
     * @generated from rpc notification.v1.NotificationService.createNotification
     */
    createNotification: {
      name: "createNotification",
      I: CreateNotificationRequest,
      O: CreateNotificationResponse,
      kind: MethodKind.Unary,
    },
  }
};

