// @generated by protoc-gen-es v1.3.0
// @generated from file notification/v1/service.proto (package notification.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Notification } from "./notification_pb.js";

/**
 * @generated from message notification.v1.CreateNotificationRequest
 */
export const CreateNotificationRequest = proto3.makeMessageType(
  "notification.v1.CreateNotificationRequest",
  () => [
    { no: 1, name: "notification", kind: "message", T: Notification },
  ],
);

/**
 * @generated from message notification.v1.CreateNotificationResponse
 */
export const CreateNotificationResponse = proto3.makeMessageType(
  "notification.v1.CreateNotificationResponse",
  () => [
    { no: 1, name: "notification_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

