// @generated by protoc-gen-connect-query v0.4.1
// @generated from file notification/v1/service.proto (package notification.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { UnaryHooks } from "@bufbuild/connect-query";
import { CreateNotificationRequest, CreateNotificationResponse } from "./service_pb.js";

export const createNotification: UnaryHooks<CreateNotificationRequest, CreateNotificationResponse>;
