// @generated by protoc-gen-es v1.1.1
// @generated from file security/v1/security.proto (package security.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message security.v1.SignInRequest
 */
export const SignInRequest = proto3.makeMessageType(
  "security.v1.SignInRequest",
  () => [
    { no: 1, name: "user_credentials", kind: "message", T: SignInRequest_UserCredentials, oneof: "credentials" },
    { no: 2, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "credentials" },
  ],
);

/**
 * @generated from message security.v1.SignInRequest.UserCredentials
 */
export const SignInRequest_UserCredentials = proto3.makeMessageType(
  "security.v1.SignInRequest.UserCredentials",
  () => [
    { no: 1, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "api_token", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
  {localName: "SignInRequest_UserCredentials"},
);

/**
 * @generated from message security.v1.SignInResponse
 */
export const SignInResponse = proto3.makeMessageType(
  "security.v1.SignInResponse",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

