// @generated by protoc-gen-connect-web v0.6.0 with parameter "target=ts"
// @generated from file security/v1/security.proto (package security.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SignInRequest, SignInResponse } from "./security_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service security.v1.SecurityService
 */
export const SecurityService = {
  typeName: "security.v1.SecurityService",
  methods: {
    /**
     * *Auth* //
     *
     * @generated from rpc security.v1.SecurityService.SignIn
     */
    signIn: {
      name: "SignIn",
      I: SignInRequest,
      O: SignInResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

