// @generated by protoc-gen-connect-web v0.11.0
// @generated from file security/v1/security.proto (package security.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SignInRequest, SignInResponse } from "./security_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service security.v1.SecurityService
 */
export declare const SecurityService: {
  readonly typeName: "security.v1.SecurityService",
  readonly methods: {
    /**
     * *Auth* //
     *
     * @generated from rpc security.v1.SecurityService.SignIn
     */
    readonly signIn: {
      readonly name: "SignIn",
      readonly I: typeof SignInRequest,
      readonly O: typeof SignInResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

