// @generated by protoc-gen-es v0.2.1 with parameter "target=js+dts"
// @generated from file device/device.proto (package spotsie.device.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3, Timestamp} from "@bufbuild/protobuf";

/**
 * @generated from message spotsie.device.v1.Device
 */
export const Device = proto3.makeMessageType(
  "spotsie.device.v1.Device",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "hardware_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "last_ping", kind: "message", T: Timestamp },
    { no: 4, name: "created_at", kind: "message", T: Timestamp },
    { no: 5, name: "sessions", kind: "message", T: Session, repeated: true },
  ],
);

/**
 * @generated from message spotsie.device.v1.Session
 */
export const Session = proto3.makeMessageType(
  "spotsie.device.v1.Session",
  () => [
    { no: 1, name: "device_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "first_ping_at", kind: "message", T: Timestamp },
    { no: 3, name: "last_ping_at", kind: "message", T: Timestamp },
  ],
);

