// @generated by protoc-gen-connect-web v0.3.1 with parameter "target=ts"
// @generated from file location/service.proto (package spotsie.location.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {GetGeoLocationHistoryRequest, GetGeoLocationHistoryResponse, GetLatestSubjectPositionRequest, GetLatestSubjectPositionResponse, GetLocationHistoryRequest, GetLocationHistoryResponse, GetRealtimeLocationRequest, GetRealtimeLocationResponse, GetSubjectLocationsAtRequest, GetSubjectLocationsAtResponse} from "./service_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service spotsie.location.v1.LocationApi
 */
export const LocationApi = {
  typeName: "spotsie.location.v1.LocationApi",
  methods: {
    /**
     * @generated from rpc spotsie.location.v1.LocationApi.GetLocationHistory
     */
    getLocationHistory: {
      name: "GetLocationHistory",
      I: GetLocationHistoryRequest,
      O: GetLocationHistoryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.location.v1.LocationApi.GetGeoLocationHistory
     */
    getGeoLocationHistory: {
      name: "GetGeoLocationHistory",
      I: GetGeoLocationHistoryRequest,
      O: GetGeoLocationHistoryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.location.v1.LocationApi.GetRealtimeLocation
     */
    getRealtimeLocation: {
      name: "GetRealtimeLocation",
      I: GetRealtimeLocationRequest,
      O: GetRealtimeLocationResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc spotsie.location.v1.LocationApi.GetSubjectLocationsAt
     */
    getSubjectLocationsAt: {
      name: "GetSubjectLocationsAt",
      I: GetSubjectLocationsAtRequest,
      O: GetSubjectLocationsAtResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spotsie.location.v1.LocationApi.GetLatestSubjectPosition
     */
    getLatestSubjectPosition: {
      name: "GetLatestSubjectPosition",
      I: GetLatestSubjectPositionRequest,
      O: GetLatestSubjectPositionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

