// @generated by protoc-gen-connect-web v0.11.0
// @generated from file telemetry/v1/service.proto (package telemetry.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetBeaconLogsRequest, GetBeaconLogsResponse, GetLatestBeaconLogsRequest, GetLatestBeaconLogsResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service telemetry.v1.TelemetryService
 */
export declare const TelemetryService: {
  readonly typeName: "telemetry.v1.TelemetryService",
  readonly methods: {
    /**
     * @generated from rpc telemetry.v1.TelemetryService.GetBeaconLogs
     */
    readonly getBeaconLogs: {
      readonly name: "GetBeaconLogs",
      readonly I: typeof GetBeaconLogsRequest,
      readonly O: typeof GetBeaconLogsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc telemetry.v1.TelemetryService.GetLatestBeaconLogs
     */
    readonly getLatestBeaconLogs: {
      readonly name: "GetLatestBeaconLogs",
      readonly I: typeof GetLatestBeaconLogsRequest,
      readonly O: typeof GetLatestBeaconLogsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

