// @generated by protoc-gen-es v1.3.0
// @generated from file telemetry/v1/telemetry.proto (package telemetry.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";
import { Beacon as Beacon$1 } from "../../domain/v1/domain_pb.js";

/**
 * @generated from message telemetry.v1.TemperatureLog
 */
export const TemperatureLog = proto3.makeMessageType(
  "telemetry.v1.TemperatureLog",
  () => [
    { no: 1, name: "time", kind: "message", T: Timestamp },
    { no: 2, name: "temperature", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message telemetry.v1.BatteryLog
 */
export const BatteryLog = proto3.makeMessageType(
  "telemetry.v1.BatteryLog",
  () => [
    { no: 1, name: "time", kind: "message", T: Timestamp },
    { no: 2, name: "voltage", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ],
);

/**
 * @generated from message telemetry.v1.ButtonPressLog
 */
export const ButtonPressLog = proto3.makeMessageType(
  "telemetry.v1.ButtonPressLog",
  () => [
    { no: 1, name: "time", kind: "message", T: Timestamp },
    { no: 2, name: "button", kind: "enum", T: proto3.getEnumType(ButtonPressLog_Button) },
  ],
);

/**
 * @generated from enum telemetry.v1.ButtonPressLog.Button
 */
export const ButtonPressLog_Button = proto3.makeEnum(
  "telemetry.v1.ButtonPressLog.Button",
  [
    {no: 0, name: "BUTTON_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "BUTTON_MAIN", localName: "MAIN"},
    {no: 2, name: "BUTTON_SECONDARY", localName: "SECONDARY"},
  ],
);

/**
 * @generated from message telemetry.v1.MovementLog
 */
export const MovementLog = proto3.makeMessageType(
  "telemetry.v1.MovementLog",
  () => [
    { no: 1, name: "time", kind: "message", T: Timestamp },
    { no: 2, name: "has_moved", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message telemetry.v1.Beacon
 */
export const Beacon = proto3.makeMessageType(
  "telemetry.v1.Beacon",
  () => [
    { no: 1, name: "ibeacon", kind: "message", T: Beacon$1, opt: true },
    { no: 2, name: "mac_address", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 3, name: "primary_key", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

